
spring:
#  使用开发环境的配置
  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    favicon:
      enabled: false
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/resources,classpath:/static,classpath:/public,classpath:/META-INF/resources,file:static/
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

